### ISSUE TITLE
NixOS SD card image reproduction Q&A

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/nixos-config-rpi#1]
@bflaggs @ZishuoYang Let's use this issue to track all problems regarding the reproduction of SD card images for our RPi 3 and 4's.

* I've restored the dropbox link listed in the README file.
* To differentiate between RPi 3 and 4 image, just take a look at the hostname of the Pi: RPi 4 has a hostname of `LabPi4`, RPi 3 `LabPi3`.

**Comment by yipengsun** [comment]
Before I leave, I left a working Pi 3 **AND** Pi 4. So if you just need two Pi's for development, you don't need to install one from scratch.

Also, I think it is fine to do testing with a Raspbian, provided that you don't override existing NixOS SD cards.

Here's a quick reference to **reconfigure** an existing NixOS setup:
```
cd /etc/nixos
git pull origin rpi4  # replace 'rpi4' with 'rpi3' if you are on 'rpi3'
sudo nixos-rebuild switch
```

If there's no error, the Pi is configured correctly. Post error messages here if you encounter problems.

**Comment by yipengsun** [comment]
The updated configuration makes `/dev/gpiomem` writable for all users in the `gpio` group (just like what Raspbian does). If you can't reconfigure it, current configuration is still workable: Just prepend a `sudo` when you do the testing:
```
sudo ./FireAlarm.py 4  # '4' is the GPIO pin number that connects to the fire alarm
```

**Comment by yipengsun** [comment]
@bflaggs If you can list the confusing parts in the README, I can try to explain it a bit better.

**Comment by bflaggs** [comment]
@yipengsun there was an error when trying to rebuild the Pi 3 system after pulling the repo `rpi3`. The output to the terminal from the command `sudo nixos-rebuild switch` is attached here: 
[rebuild_errors.txt](https://github.com/umd-lhcb/nixos-config-rpi/files/4160916/rebuild_errors.txt)


It should also be noted that we were unable to use the Pi 4 because I do not believe that the Pi 4 is properly configured. When I start up the Pi 4, NixOS will start however there is no login screen that comes up and I am immediately logged in. The terminal states something about `root` not being setup so automatic login was established. Because of this the `hostname` on the Pi 4 is `nixos` **NOT** `LabPi4` as it should be.

**Comment by yipengsun** [comment]
The error log is useful. I'll fix it soon. However, please attach the error log to the issue, instead of push it to a branch.

**Comment by yipengsun** [comment]
As for reconfiguring another Pi 3, the steps are:

1. Download one of my pre-approved images, then `dd` it to a SD card.
2. Clone this repo to `/etc/nixos` on the SD card, following instructions in README.
2. Insert the SD card to a Pi 4, now the hostname should be `nixos`
3. Configure a **temporary** password for user `nixos` (This is the default user for the installation media, and **does not exist** in the final setup) with `passwd` then type in the password of your choice.
4. Run `sudo nixos-rebuild switch` on the Pi 4.
5. Go to `/etc/nixos` in the Pi 4, switch to `pi3` branch
6. `sudo nixos-rebuild switch` again
7. Remove the SD card from Pi 4, insert it into a Pi 3.

**Comment by yipengsun** [comment]
Another thing for error log: If you have a SSH connection to the Pi, then copy the error log should be easy, otherwise I guess it's fine to just push the log to a branch to minimize trouble.

Later I/we can download the file via github web interface and attach the file here. Then I'll do a force push to remove that commit. But it is fine to use a branch as a temporary storage.

**Comment by yipengsun** [comment]
@bflaggs I've pushed a "fix" to both branches. Will you test if they work? 

Also, I've removed your commit to `rpi3` branch and attached the file in your post. If you want to pull the `rpi3` branch, I'd suggest you to do the following:
```
git reset --hard HEAD~1  # on rpi3 branch
git pull origin rpi3
```

**Comment by bflaggs** [comment]
@yipengsun I will check if they work when I come in tomorrow afternoon, which will be around 1pm EST.

As for the error logging, I do not have SSH connection to the Pi which is why we pushed directly to the `rpi3` branch. So, unfortunately, we will have to continue pushing the error log files and then rearranging the files. Hopefully no more errors arise so that we will not need to do this anymore.

**Comment by yipengsun** [comment]
For building new images, internet connection is required (to download source code of linux kernel). How'd you configure internet access on pis?

**Comment by bflaggs** [comment]
I was able to get internet access on the pis by sharing the internet from my computer. I would bridge the network connections for my laptop's WiFi and my laptop's ethernet port and then I would connect to the pi via and ethernet cord. Although doing so takes my laptop's internet connection away.

**Comment by bflaggs** [comment]
@yipengsun the fix now allows a rebuild of the system without errors. Although we still receive all of the warnings that were included in the above log file.

Now, after pulling the updates to `rpi3` and then rebuilding the system using `sudo nixos-rebuild switch`, the python scripts `WaterAlarm.py` and `FireAlarm.py` will not run as root. When running as root they both error and say that there is no module named `rpi`. A log of the terminal output is attached here:
[wateralarm_errorlog.txt](https://github.com/umd-lhcb/nixos-config-rpi/files/4167438/wateralarm_errorlog.txt)

I can still run `WaterAlarm.py` without using the command `sudo` and it seems to tun okay (I have not tested if it can detect water) although running `FireAlarm.py` without using the `sudo` command will also result in the error of no module named `rpi`.

I would delete the file I pushed (the same file included here) although I do not have write access to the repo.

For now I will continue testing the scripts by running without the `sudo` command.

**Comment by bflaggs** [comment]
I have run the command `python3` as root and not as root and have determined that the system paths (the output paths from the Python command `sys.path`) are different when running the command `sudo python3` compared to the command `python3`.

When I do not run Python 3 as root then there are more paths within the system (more paths are output when I issue the python command `sys.path`), I believe that the module `RPi` is within one of these extra paths as I am able to import module `RPi` when I am **NOT** running Python 3 as root. Although when I **DO** run Python 3 as root I am not able to import this module.

This `ModuleNotFoundError` for importing `RPi` causes the `ModuleNotFoundError` for `rpi` (the repo including the python scripts) because the import error for `RPi` occurs **within** the snippet of code below:

```
try:
    from rpi.burnin.WaterAlarm import WaterAlarm
except Exception:
    sys.path.insert(0, "..")
    from rpi.burnin.WaterAlarm import WaterAlarm
```

The `Exception` is raised and then `WaterAlarm` is imported properly **although** within `WaterAlarm` we import `RPi`, which when running as root **can not** be found. So the codes error when running as root.

I'm not sure how to fix this but I'm very confident that this is the problem. As I said in the post above I will continue debugging without running either script as root.

**Comment by yipengsun** [comment]
Now that I think of it, `root` probably can't see the Python libraries to due to how NixOS works. I think now if Fire and Water alarm scripts work as a user, then all is good. If not, I can update configuration file of NixOS so that all libraries are installed globally.

**Comment by ZishuoYang** [comment]
@yipengsun please clarify the instructions regarding mounting partitions (in the last command line, which partition should we mount?) : 

In Linux, suppose we have a sdcard mmcblk0 with 2 partitions mmcblk0p1 and mmcblk0p1, then we should write to mmcblk0, not either of the partitions, with the following command:

sudo dd if=<nixos.img> of=/dev/mmcblk0
On first boot, the rootfs will be automatically resized to use all available spaces of the SD card.
After the dd command is completed, mount the /dev/mmcblk0p2 to /mnt:

sudo mount /dev/mmcblk0p1 /mnt

**Comment by yipengsun** [comment]
The latter of the two (`p1`). Apparently I can't count properly but you should know me well enough by now to not trust me counting :-)

Lemme fix that in the `README.md` as well.

**Comment by bflaggs** [comment]
@yipengsun when configuring a microSD card on the rpi 4, after running the command `sudo nixos-rebuild switch` and rebooting the pi, the user `lhcb` is not created. On the rpi 4 there is still no actual login and the user is `nixos@nixos`. I also listed the contents of the file `/etc/passwd` and there was no user with the name `lhcb`.

It is worth mentioning that when I ran the command `sudo mount /dev/mmcblk0p1 /boot` I received an error stating `mount: /boot: mount point does not exist.`. To correct this error I just made the `/boot` directory using `sudo` privileges.

Another error I received that might be important is after I ran the command `sudo nixos-rebuild switch`, the command directly after mounting the boot partition, I received the error that the file `/etc/nixos/configuration.nix` did not exist. I also ignored this error because in your README file it says to ignore warnings and errors that occur during that step.

**Comment by yipengsun** [comment]
> It is worth mentioning that when I ran the command `sudo mount /dev/mmcblk0p1 /boot` I received an error stating `mount: /boot: mount point does not exist.`

This is an indication that the root partition is not set up correctly. In my last post, I claimed that you should do this:
```
sudo mount /dev/mmcblk0p1 /mnt
```

Under the assumption that `p1` is the **second** partition. That **is wrong**: My initial recollection told me that partitions should start with `0`. When I wake up today, I think I was wrong: partition should start with `1`! **Sorry!**. You can confirm this by checking the partitioning scheme with `lsblk`.

Try the following mount (old instruction):
```
sudo mount /dev/mmcblk0p2 /mnt
```
After that mount, you can cd into `/mnt` and folder `boot` should be there. 

If not, then the disk image is not properly written to the SD card. If you are using a pi 4 to recreate another SD card image with a USB card reader, You need to be careful about the path to the disk: The USB card reader **could** (again, check with `lsblk`) map the SD card to something like `/dev/sda`, not `/dev/mmcblkX` (This depends on the hardware).

EDIT: To identify the **root** partition of NixOS: It's the one with `nix` folder after mounting it.

> Another error I received that might be important is after I ran the command `sudo nixos-rebuild switch`, the command directly after mounting the boot partition, I received the error that the file `/etc/nixos/configuration.nix` did not exist. I also ignored this error because in your README file it says to ignore warnings and errors that occur during that step.

This error is indeed too serious to ignore. Follow my troubleshooting guide listed in the above paragraph.

**Comment by yipengsun** [comment]
Given the difficulties recreating SD cards, If we still have two working NixOS pi's (one for pi3, one for pi4), I think you can use Raspbian for the rest of the pi for easier setup. The NixOS systems can be reserved for burn-in servers only.

**Comment by yipengsun** [comment]
It's too bad that I can't SSH into my computer on my desktop, otherwise I can do these things remotely (after connecting pi to my desktop, with a working initial SD card image).

**Comment by yipengsun** [comment]
Another point: One of my initial motivation to switch to NixOS is: People keep re-installing Raspbians on my old Arch linux rpi SD cards, which means all my previous configurations were lost. The good thing about NixOS is that **I** (not everybody) can recreate my old setup with ease so that the rest of us can use Raspbians freely.

I think this is the correct way to go: Install Raspbians on the new SD cards while keeping the old NixOS ones for burn-in servers. You probably still need to do some debugging on NixOS, but you don't need to making new NixOS images.

**Comment by bflaggs** [comment]
I do believe that when we attach the USB card reader it does have a path of `/dev/sda` **not** `/dev/mmcblkX`. Zishuo would know more about how the mounting part of this worked as he was the one who performed this part yesterday. I can also take a look and see if this is the case.

As for what you think is the correct way to go I will check with Manuel and Zishuo when they arrive today and see if they agree. **However**, when you left you said that there was a working/configured rpi 4 although the only rpi 4 that we could find was one that did not seem to be fully setup. I briefly mentioned this in the 2nd paragraph of this post https://github.com/umd-lhcb/nixos-config-rpi/issues/1#issuecomment-582481249.

**Comment by yipengsun** [comment]
I see. It's possible that I forgot to fully configure pi 4, as I was using my own SD card on pi 4 and may forgot fully configure the SD card that was installed.

You could use the same instruction guide to re-configure that pi 4. I guess you should mount `mmcblk2/sdX2` to `/mnt` and clone the content of this project to `/mnt/etc/nixos`.

It would be better if we can schedule a meeting and you can show me your procedure.

**Comment by yipengsun** [comment]
I'm planning to talk to Manuel 10am EST. @bflaggs maybe we can talk afterwards?

**Comment by bflaggs** [comment]
That works for me, did you want to talk via slack?

**Comment by bflaggs** [comment]
Also I have the procedure typed out in my notes up to the part labeled **System Configuration** in your README. Again Zishuo figured out the way to do this and I just typed what he told me and how I understood it although I could send you what I have.

**Comment by bflaggs** [comment]
This was everything that I did to fully configure a pi 4 with NixOS and then fully configure a pi 3 with NixOS.

I was able to fully configure a pi 4 with NixOS by following the following steps:

**Follow instructions below to install the OS.**

1. Save Yipeng's image file to USB memory stick.
2. Insert memory stick to rpi3 with configured a microSD card in microSD slot.
3. Save Yipeng's image file from USB stick to configured microSD card (just make a new directory under the `/home` directory called `image_file_to_install` or something and save it here).
4. Unzip the image file (because it should be zipped as a `.bz2` file) using the command `bzip2 -dk <name_of_bz2_image_file>`.
5. Insert USB converter stick with unconfigured microSD card in the SD slot (Check the name of this new microSD card by doing `ls /dev` before and after inserting this USB converter. **NOTE:** Typically the name of the unconfigured microSD card will be `sda` with two partitions `sda1` and `sda2`). 
6. If microSD card has name `sda` then use command `sudo dd if=<path_to_nixos.img> of=/dev/sda`  in order to setup NixOS on the unconfigured mircoSD card (**NOTE:** if microSD card does not have name `sda` then replace `sda` in the command with whatever the name of the microSD card appears to be in the `/dev` directory)
7. Mount the microSD card using command `sudo mount /dev/sda2 /mnt`.
8. Clone the rpi4 NixOS configuration from GitHub (**NOTE:** The `mkdir` and all the subsequent git commands to be executed in this step must be run as root, this step is outlined here: https://github.com/umd-lhcb/nixos-config-rpi).
9. Unmount the microSD card using command `sudo umount /mnt`.
10. Unplug microSD card from USB on rpi4 and plug into microSD slot on rpi4.

**Follow instructions below to set up the OS.**

1. On first boot of the pi set the password with command `sudo passwd root` (enter any password you like, this password does not matter and will be erased soon).
2. Switch to root user using command `su`.
3. Issue command `ls /` and look to see if directory `/boot` exists, if so move to step 5.
4. Create the `/boot` directory using the command `sudo mkdir /boot`.
5. Mount the boot partition using the command `sudo mount /dev/mmcblk0p1 /boot` (**NOTE:** Here we mount using `mmcblk0p1` because the microSD card is now in the mircroSD slot not in the USB slot. Also notice here we mount using partition, i.e. `0p1` , because this partition is where the contents which need to go into the `/boot` directory are saved.).
6. Rebuild the system using `sudo nixos-rebuild switch` (there will be errors at this step which will be okay because the SD card will not be fully setup yet **HOWEVER**, if you receive an error stating the `etc/nixos/configuration.nix` file could not be found and the build starts erroring A LOT then there is a bigger error. Most likely something was not setup correctly in one of the previous steps such as either branch `rpi4` was not cloned correctly from GitHub or the wrong microSD partition was mounted).
7. Perform the command `sudo poweroff` in order to shut off the pi, disconnect power from the wall and then plug back in to reboot. (**NOTE:** You do not need to unmount the partition before powering off as the pi will automatically unmount the partition once it receives the signal to power off.).
8. On reboot perform steps 2-7 **again and exactly as they are described above** (if `/boot` directory does not exist and you need to remake it after rebooting then you did something wrong along the way).
9. Now the user `lhcb` should have been made, perform command `less /etc/passwd` in order to check the users on the system. Make sure that `lhcb` is an actual user and the move to the next step. If there is no user with this name then you have done something wrong, reboot and try steps 2-7 again.
10. Again reboot the system following the actions outlined in step 7.
11. On reboot you should be asked for the login of `LabPi4` (only if you are on the pi 4), login with user `lhcb` where the password is the same as the username. The reboot will also state something about zshell not being completely configured, when it asks for an input you can read the answers it expects and do one of those commands. I performed command `0` stating just to put a comment in the zshell file so that this warning would not pop-up again.
12. If everything looks good/normal then we can add the official unstable package using command `sudo nix-channel --add --add https://nixos.org/channels/nixos-unstable nixos`.
13. Update the system again using the command `sudo nixos-rebuild switch --upgrade`.
14. If upgrading the system works then you can delete the old unnecessary files with command `sudo nix-collect-garbage -d`.

**Note:** The above configuration is for setting up the microSD card for a pi 4. 

To set up the microSD card for a pi 3 then follow the steps exactly as outlined above then perform the following steps afterwards:

1. Make sure that the microSD card is plugged into a pi 4 and is fully setup to work correctly with NixOS.
2. Change directory into where the `nixos-config-rpi` repo is set using the command `cd /etc/nixos`.
3. Run the commands `sudo git fetch origin` then `sudo git checkout rpi3` in order to switch to branch `rpi3`.
4. Remove all the files in the `/boot` directory using the command `sudo rm -rf /boot/*`. This is because the boot directory is too small to hold everything it needs.
5. Rebuild the system using command `sudo nixos-rebuild switch`. **NOTE:** Yipeng says in his README on branch `rpi3` that this step will take~3 hours to complete because the rpi3 kernel needs to manually compile **however**, if the commands are run in this exact way where you setup the rpi4 kernel before the rpi3 kernel then this rebuilding only takes a few minutes.
6. Now poweroff the pi 4 using `sudo poweroff` then plug the microSD card into a pi 3 and everything should be configured.
